//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServerEntityFramework.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChatMasterEntities : DbContext
    {
        public ChatMasterEntities()
            : base("name=ChatMasterEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<LOGIN> LOGINs { get; set; }
        public DbSet<MESSAGEMAST> MESSAGEMASTs { get; set; }
        public DbSet<USERINFO> USERINFOes { get; set; }
        public DbSet<CONNECTION> CONNECTIONS { get; set; }
        public DbSet<ONLINEUSER> ONLINEUSERS { get; set; }
        public DbSet<employee> employees { get; set; }
    }
}
