//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServerEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONNECTION
    {
        public int ID { get; set; }
        public Nullable<int> FROM_USER { get; set; }
        public Nullable<int> TO_USER { get; set; }
    }
}
