//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServerEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN
    {
        public LOGIN()
        {
            this.USERINFOes = new HashSet<USERINFO>();
        }
    
        public int ID { get; set; }
        public string UID { get; set; }
        public string UPWD { get; set; }
    
        public virtual ICollection<USERINFO> USERINFOes { get; set; }
    }
}
