//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServerEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGEMAST
    {
        public int ID { get; set; }
        public int TO_USER { get; set; }
        public int FROM_USER { get; set; }
        public string MSG { get; set; }
        public Nullable<bool> PARTIAL { get; set; }
        public Nullable<System.DateTime> SENDTIME { get; set; }
        public Nullable<bool> DELIVERED { get; set; }
    
        public virtual USERINFO USERINFO { get; set; }
        public virtual USERINFO USERINFO1 { get; set; }
    }
}
