//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServerEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ONLINEUSER
    {
        public int ID { get; set; }
        public int USERID { get; set; }
    
        public virtual USERINFO USERINFO { get; set; }
    }
}
